//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EliteDangerous_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commodities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commodities()
        {
            this.listings = new HashSet<listings>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<decimal> average_price { get; set; }
        public int category_id { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<listings> listings { get; set; }
    }
}
