//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EliteDangerous_test.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EliteDangerousEntities : DbContext
    {
        public EliteDangerousEntities()
            : base("name=EliteDangerousEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Commodities> Commodities { get; set; }
        public virtual DbSet<export_commodities> export_commodities { get; set; }
        public virtual DbSet<import_commodities> import_commodities { get; set; }
        public virtual DbSet<listings> listings { get; set; }
        public virtual DbSet<prohibited_commodities> prohibited_commodities { get; set; }
        public virtual DbSet<Station> Station { get; set; }
        public virtual DbSet<Station_lite> Station_lite { get; set; }
        public virtual DbSet<Systems> Systems { get; set; }
    }
}
