//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EliteDangerous_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class import_commodities
    {
        public int Id_Station { get; set; }
        public string name { get; set; }
    
        public virtual Station_lite Station_lite { get; set; }
    }
}
