//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EliteDangerous_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Station()
        {
            this.listings = new HashSet<listings>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<int> system_id { get; set; }
        public string max_landing_pad_size { get; set; }
        public Nullable<int> distance_to_star { get; set; }
        public string faction { get; set; }
        public string government { get; set; }
        public string allegiance { get; set; }
        public string state { get; set; }
        public string type { get; set; }
        public Nullable<bool> has_blackmarket { get; set; }
        public Nullable<bool> has_commodities { get; set; }
        public Nullable<bool> has_refuel { get; set; }
        public Nullable<bool> has_repair { get; set; }
        public Nullable<bool> has_rearm { get; set; }
        public Nullable<bool> has_outfitting { get; set; }
        public Nullable<bool> has_shipyard { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<listings> listings { get; set; }
        public virtual Systems Systems { get; set; }
    }
}
